scraper_image: gcr.io/answers-engine-cloud/scraper-worker@sha256:aea5f89cea181c1dd24397cac3285f58d0072b7ab91153786c1da3bc1176305f
seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false