seeder:
  file: ./seeder/seeder.rb
  disabled: false
finisher:
  file: ./finisher/finisher.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false
exporters:
  - file: ./exporters/products_last10_json.yaml
    disabled: false
  - file: ./exporters/products_json.yaml
    disabled: false
  - file: ./exporters/products_csv.yaml
    disabled: false
input_vars:
  - name: start_url
    title: Start URL
    description: Enter the starting page for the scraper to run
    default: https://www.ebay.com/sch/i.html?_nkw=macbooks
    type: text
    required: true
  - name: secret1
    type: secret
    required: true
  - name: date1
    type: date
  - name: datetime1
    type: datetime
  - name: string1
    type: string
  - name: text1
    type: text
  - name: defaulttext1
    type: text
    default: somedefault text