scraper_image: gcr.io/answers-engine-cloud/tordatascience-scraper-worker-s3cmd
seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false